apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name     : root
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name     : in-cluster
    server: https://kubernetes.default.svc
    namespace: argocd
  source:
    path   : "demo-dev/applications"
    repoURL: "git@github.com:nieznajomiec/argocd.git"
    targetRevision: HEAD
  project: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune   : true
      selfHeal: true
      
